# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
<html>
<audio src="http://www.30milkshakes.com/mp3blog/cyndi_lauper_-_girls_just_want_to_have_fun.mp3" controls preload="auto" autobuffer autoplay></audio>
</html>
# Site settings
title: Catastic
email: Nekoismyfavoritecat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello weirdos I've invited to my website, I don't know why I told you about it but how else would one brag?
  This site is dedicated to the concept of "cat"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whatthecat.net" # the base hostname & protocol for your site
twitter_username: CatasticNeko
github_username:  Bullwalrus

# Build settings
markdown: kramdown
